wordpress:
  image: chip/zehn.de:v1
  ports:
    - 8080:80
  volumes:
    - /opt/share/zehn.de:/var/www/html/wp-content/uploads
  links:
      - db:mysql
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example